title: Alok Kumar
logo: /assets/img/Alok_Img.jpg
description: 
Experienced in the field of Embedded Applications and User Interfaces
software for Avionics/Aerospace majors, using the industry standard 
tools/Languages with overall Software Development Experience of more 
than 9 years. Proficient in Analysis, Design, Development, 
Verification and Validation of various Cockpit Communications, 
Display Systems and Aircraft Navigation Applications.

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
